ontology_file = open('ontology1.rdf', 'w')
ontology_file.write('<?xml version="1.0" ?>\n')
ontology_file.write('<rdf:RDF\n')
ontology_file.write('xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n')
ontology_file.write('xmlns:owl="http://www.w3.org/2002/07/owl#"\n')
ontology_file.write('xmlns:xml="http://www.w3.org/XML/1998/namespace"\n')
ontology_file.write('xmlns:xsd="http://www.w3.org/2001/XMLSchema#"\n')
ontology_file.write('xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"\n')
ontology_file.write('xmlns:prj="http://localhost/onto/proj/">\n')
ontology_file.write('<owl:Ontology rdf:about="http://localhost/onto/proj/"/>\n')
ontology_file.write('<owl:Class rdf:about="http://localhost/onto/proj/#Phone"/>\n')
predicateList = open('predicatelist.txt', 'r')
for line in predicateList:
    lineTemp = line.split('||')
    if(lineTemp[1] =='sub\n'):
        ontology_file.write('<owl:ObjectProperty rdf:about="http://localhost/onto/proj/'+lineTemp[0].replace(' ', '').replace('&', '')+'" rdfs:label="'+lineTemp[0].replace(' ', '').replace('&', '')+'">\n')
        ontology_file.write('<rdfs:domain rdf:resource="http://localhost/onto/proj/#Phone"/>\n')
        ontology_file.write('<rdfs:isDefinedBy rdf:about="http://localhost/onto/proj/"/>\n')
        ontology_file.write('</owl:ObjectProperty>\n')
    else:
        a = lineTemp[0].replace(' ', '').replace('&', '')
        if (lineTemp[0] == 'Thông tin khác' and lineTemp[1] != 'sub\n'):
            a = lineTemp[0].replace(' ', '').replace('&', '')+lineTemp[1][0:len(lineTemp[1])-1].replace(' ', '').replace('&', '')
        ontology_file.write('<owl:ObjectProperty rdf:about="http://localhost/onto/proj/'+a+'" rdfs:label="'+a+'">\n')
        ontology_file.write('<rdfs:subPropertyOf rdf:resource="http://localhost/onto/proj/'+lineTemp[1][0:len(lineTemp[1])-1].replace(' ', '').replace('&', '')+'"/>\n')
        ontology_file.write('<rdfs:domain rdf:resource="http://localhost/onto/proj/#Phone"/>\n')
        ontology_file.write('<rdfs:isDefinedBy rdf:about="http://localhost/onto/proj/"/>\n')
        ontology_file.write('</owl:ObjectProperty>\n')
ontology_file.write('</rdf:RDF>\n')
ontology_file.close()
